name: test
on: push
#  push:
#    branches:
#      - develop
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: Zettabyte
          SSH_HOST: 158.160.5.48

      - name: Stop the server
        run: ssh staging 'ls'

      - name: Check out the source
        run: ssh staging 'ls -l /home'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'cd /home'
