name: test

on:
  push:
    branches:
      - develop

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: list of changed files
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - name: Add ssh key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
      - name: update files
        env: 
          options: ssh -i ~/.ssh/key -o StrictHostKeyChecking=no
        run: rsync -e "$options" --archive -ac ./ zettabyte@158.160.5.48:/home/html
      - name: run command
        run: ssh -i ~/.ssh/key zettabyte@158.160.5.48 'ls'
      - name: run another command
        run: ssh -i ~/.ssh/key zettabyte@158.160.5.48 'cd /home/zettabyte/Regolith/cab* && npm install'
